services:
  # バックエンド+フロントエンドを統合したウェブサービス
  - type: web
    name: hidden-image-generator
    env: python
    buildCommand: npm install && npm run build && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: uploads
      mountPath: /opt/render/project/src/files
      sizeGB: 1
