services:
  # バックエンド（FastAPI）
  - type: web
    name: pozt-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STATIC_DIR
        value: static
    
  # フロントエンド（React）
  - type: web
    name: pozt-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: pozt-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
