services:
  - type: web
    name: pozt
    env: python
    buildCommand: ./build.sh
    startCommand: >
      cd backend &&
      PYTHONPATH=$PYTHONPATH:$(pwd)
      python -m uvicorn main:app
      --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"

